### ISSUE TITLE
Run our own bootstrap nodes

### ISSUE THREAD

**Issue by jihoonsong** [topology-foundation/ram-monorepo#2]
**Describe the problem you are trying to solve**
Currently, we're using IPFS's default bootstrap nodes. Having our own bootstrap nodes that are configurable by us and designated for our purpose is needed.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Describe why the solution is optimal**
A clear and concise description of the rationale for the solution you're proposing.

**Additional context**

**Comment by 0xMugen** [comment]
I'll add bootstrap deployment connection in the config file. With a default for ipfs is they aren't responsive or valid. 
Are there any specific providers you want to use for the bootstrap node deployment?

**Comment by jihoonsong** [comment]
Do you mean it failed to connect to other peers using default bootstrap node? Actually, it works as is, I tested it by myself, but it just takes some minutes. I think it's because the default ones also have dead logs of disconnected peers and we're trying to connect to them first, which is unnecessary. It's one of reasons why we need our own bootstrap node; we can configure it as we want even for ease of development.

While we're using the default ones, a simple but stupid mitigation is changing `namespace` of config. Specifying some random string will do.

**Comment by jihoonsong** [comment]
For anyone who'd work on this, I think you need to work on a separate repo. Please ask us to make one for you, you can transfer to us or let us fork yours. Don't forget to test it over the internet before raise a PR. Afterward, as it should remain hot, Topology will host bootstrap nodes (in terms of billing).

When it comes to tech stack, using libp2p's Kademlia DHT will do. Any language is okay as long as it's easy to maintain and reliable, but as we're using Go currently, go-libp2p is preferred.

**Comment by 0xMugen** [comment]
I simply wanted to add a bootstrap node list in the config.json

**Comment by 0xMugen** [comment]
I can start this up. Are there any specific guildlines for where to deploy the bootstrap nodes, or should I just try to find the cheapest most reliable host?

**Comment by jihoonsong** [comment]
Adding a list of bootstrap nodes to the config.json and using it sounds kind of a must. It will require some changes of `network/p2p.go`. Do you want to do it in PR#8 or in the upcoming one?

**Comment by jihoonsong** [comment]
I think we can add bootstrap node at `cmd/bootstrap/main.go` and move current `cmd/main.go` to `cmd/gram/main.go`. The code of bootstrap node will be just around 100~200 LoC depending on a implementation.

You can find free or the cheapest one only to test if it works. No need to maintain it afterward unless you want to.

**Comment by 0xMugen** [comment]
Should some CD be set up for updating the bootstrap nodes automagicaly from main?

**Comment by 0xMugen** [comment]
continuous deployment, to update the deployed nodes directly from github

**Comment by jihoonsong** [comment]
It will be handled with #10. But bootstrap node is rare to be modified after it's deployed so I think setting up CD for bootstrap node is over engineering.

**Comment by jihoonsong** [comment]
Can I get an update of this? @0xMugen

**Comment by 0xMugen** [comment]
I've been pretty busy these past days. I've wrote ou the bootstrap nodes, I just need to test out the bootstrap nodes on a deployed VM. I'll get to it this evening.

**Comment by jihoonsong** [comment]
If setting up a cloud instance is too much hassle, you can consider services like [AWS Elastic Beanstalk](https://docs.aws.amazon.com/ko_kr/elasticbeanstalk/latest/dg/Welcome.html).

**Comment by 0xMugen** [comment]
Sry I've been running a bit late do to some important meetings. But I've advanced a bit. I merged the docker PR to my fork and was thinking of implementing docker for the bootstrap nodes, wdyt? Also should adding a seperate config for the bootstrap nodes is worth it, or maybe putting an override in the main config as a isNodeBootstrap param. @jihoonsong

**Comment by jihoonsong** [comment]
Bootstrap config should be independent of gram's config. Regarding the structure, you can refer to [this](https://github.com/topology-foundation/gram/issues/2#issuecomment-2020627163) comment.

Using docker looks fine for now. After we have more features, we'll set up a proper testing suite going through real ones.

**Comment by jihoonsong** [comment]
As we need this one to be done, we had to switch implementor. For more details, please see [this](https://github.com/topology-foundation/gram/pull/23#issuecomment-2088448976).
